runtime: python
api_version: 1
threadsafe: true
entrypoint: gunicorn -b :$PORT main:app
runtime_config:
  python_version: 3
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  max_concurrent_requests: 2
